version: '3.8'
services:
  tpspeek:
    build: .
    container_name: tpspeek_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_EXTERNAL_STT_TTS=${USE_EXTERNAL_STT_TTS}
    volumes:
      - ./backend/app:/app
      - ./data:/data
