name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: main
          pr_title: "Auto PR: ${{ github.ref_name }}"
          pr_body: "สร้าง Pull Request อัตโนมัติจาก branch `${{ github.ref_name }}`"
          github_token: ${{ secrets.GITHUB_TOKEN }}
